### ISSUE TITLE
[BUG] Invalid route name, already in use: 'rails_service_blob'

### ISSUE THREAD

**Issue by BenSturmfels** [houdiniproject/houdini#1046]
As @iRunner mentioned in [#524](https://github.com/houdiniproject/houdini/issues/524#issuecomment-808832810), the `bin/rails server --environment=production` fails for me with an error`Invalid route name, already in use: 'rails_service_blob'`. This running the recent `main` branch on a Debian Bullseye VM with Ruby 2.7.4 and Bundler 2.2.5.

Removing `config/routes.rb` lines 292-305 appears to fix the issue, allowing the server to start up. These lines appear to be nearly identical to `gems/activestorage-6.1.5/config/routes.rb` lines 3-17 except for a minor difference in the last line.

I'm also seeing the same on my local Guix operating system, so it doesn't appear to be specific to the above VM.

```
$ bin/rails server --environment=production
=> Booting Puma
=> Rails 6.1.5 application starting in production 
=> Run `bin/rails server --help` for more startup options
Exiting
Traceback (most recent call last):
	70: from bin/rails:9:in `<main>'
	69: from /home/debian/houdini/mygems/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	68: from /home/debian/houdini/mygems/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	67: from /home/debian/houdini/mygems/gems/railties-6.1.5/lib/rails/commands.rb:18:in `<main>'
	66: from /home/debian/houdini/mygems/gems/railties-6.1.5/lib/rails/command.rb:48:in `invoke'
	65: from /home/debian/houdini/mygems/gems/railties-6.1.5/lib/rails/command/base.rb:69:in `perform'
	64: from /home/debian/houdini/mygems/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	63: from /home/debian/houdini/mygems/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	62: from /home/debian/houdini/mygems/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	61: from /home/debian/houdini/mygems/gems/railties-6.1.5/lib/rails/commands/server/server_command.rb:135:in `perform'
	60: from /home/debian/houdini/mygems/gems/railties-6.1.5/lib/rails/commands/server/server_command.rb:135:in `tap'
	59: from /home/debian/houdini/mygems/gems/railties-6.1.5/lib/rails/commands/server/server_command.rb:144:in `block in perform'
	58: from /home/debian/houdini/mygems/gems/railties-6.1.5/lib/rails/commands/server/server_command.rb:39:in `start'
	57: from /home/debian/houdini/mygems/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
	56: from /home/debian/houdini/mygems/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
	55: from /home/debian/houdini/mygems/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
	54: from /home/debian/houdini/mygems/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
	53: from /home/debian/houdini/mygems/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
	52: from /home/debian/houdini/mygems/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	51: from /home/debian/houdini/mygems/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
	50: from /home/debian/houdini/mygems/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
	49: from /home/debian/houdini/mygems/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
	48: from /home/debian/houdini/mygems/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
	47: from config.ru:5:in `block in <main>'
	46: from config.ru:5:in `require_relative'
	45: from /home/debian/houdini/config/environment.rb:12:in `<main>'
	44: from /home/debian/houdini/mygems/gems/railties-6.1.5/lib/rails/application.rb:391:in `initialize!'
	43: from /home/debian/houdini/mygems/gems/railties-6.1.5/lib/rails/initializable.rb:60:in `run_initializers'
	42: from /usr/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
	41: from /usr/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
	40: from /usr/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
	39: from /usr/lib/ruby/2.7.0/tsort.rb:347:in `call'
	38: from /usr/lib/ruby/2.7.0/tsort.rb:347:in `each'
	37: from /usr/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
	36: from /usr/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
	35: from /usr/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	34: from /usr/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
	33: from /home/debian/houdini/mygems/gems/railties-6.1.5/lib/rails/initializable.rb:61:in `block in run_initializers'
	32: from /home/debian/houdini/mygems/gems/railties-6.1.5/lib/rails/initializable.rb:32:in `run'
	31: from /home/debian/houdini/mygems/gems/railties-6.1.5/lib/rails/initializable.rb:32:in `instance_exec'
	30: from /home/debian/houdini/mygems/gems/railties-6.1.5/lib/rails/application/finisher.rb:129:in `block in <module:Finisher>'
	29: from /home/debian/houdini/mygems/gems/activesupport-6.1.5/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
	28: from /home/debian/houdini/mygems/gems/activesupport-6.1.5/lib/active_support/lazy_load_hooks.rb:51:in `each'
	27: from /home/debian/houdini/mygems/gems/activesupport-6.1.5/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
	26: from /home/debian/houdini/mygems/gems/activesupport-6.1.5/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
	25: from /home/debian/houdini/mygems/gems/activesupport-6.1.5/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
	24: from /home/debian/houdini/mygems/gems/activesupport-6.1.5/lib/active_support/lazy_load_hooks.rb:68:in `block in execute_hook'
	23: from /home/debian/houdini/mygems/gems/devise-4.8.1/lib/devise/rails.rb:17:in `block in <class:Engine>'
	22: from /home/debian/houdini/mygems/gems/railties-6.1.5/lib/rails/application.rb:169:in `reload_routes!'
	21: from /home/debian/houdini/mygems/gems/railties-6.1.5/lib/rails/application/routes_reloader.rb:21:in `reload!'
	20: from /home/debian/houdini/mygems/gems/railties-6.1.5/lib/rails/application/routes_reloader.rb:47:in `load_paths'
	19: from /home/debian/houdini/mygems/gems/railties-6.1.5/lib/rails/application/routes_reloader.rb:47:in `each'
	18: from /home/debian/houdini/mygems/gems/railties-6.1.5/lib/rails/application/routes_reloader.rb:47:in `block in load_paths'
	17: from /home/debian/houdini/mygems/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
	16: from /home/debian/houdini/mygems/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
	15: from /home/debian/houdini/mygems/gems/activestorage-6.1.5/config/routes.rb:3:in `<main>'
	14: from /home/debian/houdini/mygems/gems/actionpack-6.1.5/lib/action_dispatch/routing/route_set.rb:409:in `draw'
	13: from /home/debian/houdini/mygems/gems/actionpack-6.1.5/lib/action_dispatch/routing/route_set.rb:427:in `eval_block'
	12: from /home/debian/houdini/mygems/gems/actionpack-6.1.5/lib/action_dispatch/routing/route_set.rb:427:in `instance_exec'
	11: from /home/debian/houdini/mygems/gems/activestorage-6.1.5/config/routes.rb:4:in `block in <main>'
	10: from /home/debian/houdini/mygems/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:901:in `scope'
	 9: from /home/debian/houdini/mygems/gems/activestorage-6.1.5/config/routes.rb:5:in `block (2 levels) in <main>'
	 8: from /home/debian/houdini/mygems/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:718:in `get'
	 7: from /home/debian/houdini/mygems/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:765:in `map_method'
	 6: from /home/debian/houdini/mygems/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1663:in `match'
	 5: from /home/debian/houdini/mygems/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1915:in `map_match'
	 4: from /home/debian/houdini/mygems/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1915:in `each'
	 3: from /home/debian/houdini/mygems/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1921:in `block in map_match'
	 2: from /home/debian/houdini/mygems/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1957:in `decomposed_match'
	 1: from /home/debian/houdini/mygems/gems/actionpack-6.1.5/lib/action_dispatch/routing/mapper.rb:1986:in `add_route'
/home/debian/houdini/mygems/gems/actionpack-6.1.5/lib/action_dispatch/routing/route_set.rb:587:in `add_route': Invalid route name, already in use: 'rails_service_blob'  (ArgumentError)
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here: 
https://guides.rubyonrails.org/routing.html#restricting-the-routes-created
```

```
$ git rev-parse --short HEAD
95be1138
```

```
$ gem list

*** LOCAL GEMS ***

action_mailer_matchers (1.2.0)
actioncable (6.1.5)
actionmailbox (6.1.5)
actionmailer (6.1.5)
actionpack (6.1.5)
actiontext (6.1.5)
actionview (6.1.5)
activejob (6.1.5)
activemodel (6.1.5)
activerecord (6.1.5)
activestorage (6.1.5)
activesupport (6.1.5)
addressable (2.8.0)
ast (2.4.2)
async (1.30.1)
async-container (0.16.12)
async-io (1.32.2)
bcrypt (3.1.16)
benchmark (default: 0.1.0)
bigdecimal (default: 2.0.0)
bootsnap (1.11.1)
builder (3.2.4)
bundler (2.2.5, default: 2.1.4)
cgi (default: 0.1.0)
chronic (0.10.2)
colorize (0.8.1)
concurrent-ruby (1.1.9)
connection_pool (2.2.5)
console (1.13.1)
countries (4.2.2)
crack (0.4.5)
crass (1.0.6)
css_parser (1.9.0)
csv (default: 3.1.2)
dante (0.2.0)
database_cleaner (1.99.0)
database_cleaner-active_record (1.99.0)
date (3.0.3, default: 3.0.0)
dbm (default: 1.1.0)
debug (1.4.0)
delegate (default: 0.1.0)
devise (4.8.1)
devise-async (1.0.0)
did_you_mean (default: 1.4.0)
diff-lcs (1.5.0)
domain_name (0.5.20190701)
dotenv (2.7.6)
dotenv-rails (2.7.6)
erubi (1.10.0)
et-orbi (1.2.5)
etc (default: 1.1.0)
execjs (2.8.1)
factory_bot (6.2.0)
factory_bot_rails (6.2.0)
fast_blank (1.0.1)
fcntl (default: 1.0.0)
ffi (1.15.5)
fiber-local (1.0.0)
fiddle (default: 1.0.0)
fileutils (default: 1.4.1)
forwardable (default: 1.3.1)
fugit (1.5.2)
gdbm (default: 2.1.0)
getoptlong (default: 0.1.0)
globalid (1.0.0)
good_job (1.99.1)
hamster (3.0.0)
hashdiff (1.0.1)
htmlentities (4.3.4)
http-accept (1.7.0)
http-cookie (1.0.3)
http_accept_language (2.1.1)
httparty (0.20.0)
i18n (1.10.0)
i18n_data (0.15.0)
image_processing (1.12.2)
io-console (0.5.11, default: 0.5.6)
ipaddr (default: 1.2.2)
irb (1.4.1, default: 1.2.6)
jbuilder (2.11.5)
json (default: 2.3.0)
kaminari (1.2.2)
kaminari-actionview (1.2.2)
kaminari-activerecord (1.2.2)
kaminari-core (1.2.2)
libv8-node (15.14.0.1 x86_64-linux-musl)
listen (3.7.1)
logger (default: 1.4.2)
lograge (0.11.2)
loofah (2.14.0)
mail (2.7.1)
mapping (1.1.1)
marcel (1.0.2)
matrix (default: 0.2.0)
method_source (1.0.0)
mime-types (3.3.1)
mime-types-data (3.2021.0901)
mini_magick (4.11.0)
mini_mime (1.1.2)
mini_portile2 (2.8.0)
mini_racer (0.4.0)
minitest (5.15.0, 5.13.0)
money (6.16.0)
msgpack (1.4.5)
multi_json (1.15.0)
multi_xml (0.6.0)
mutex_m (default: 0.1.0)
net-pop (default: 0.1.0)
net-smtp (default: 0.1.0)
net-telnet (0.1.1)
netrc (0.11.0)
nio4r (2.5.8)
nokogiri (1.13.3 x86_64-linux)
observer (default: 0.1.0)
open3 (default: 0.1.0)
openssl (default: 2.1.2)
orm_adapter (0.5.0)
ostruct (default: 0.2.0)
parallel (1.21.0)
parser (3.1.1.0)
pg (1.3.4)
power_assert (2.0.1, 1.1.7)
premailer (1.15.0)
premailer-rails (1.11.1)
prime (default: 0.1.1)
pstore (default: 0.1.0)
psych (default: 3.1.0)
public_suffix (4.0.6)
puma (5.6.2)
raabro (1.4.0)
racc (1.6.0, default: 1.4.16)
rack (2.2.3)
rack-attack (5.4.2)
rack-proxy (0.7.2)
rack-ssl (1.4.1)
rack-test (1.1.0)
rack-timeout (0.6.0)
rails (6.1.5)
rails-dom-testing (2.0.3)
rails-html-sanitizer (1.4.2)
rails-i18n (6.0.0)
railties (6.1.5)
rainbow (3.1.1)
rake (13.0.3, 12.3.3)
rb-fsevent (0.11.0)
rb-inotify (0.10.1)
rdoc (default: 6.2.1.1)
react_on_rails (12.6.0)
readline (default: 0.0.2)
readline-ext (default: 0.1.0)
regexp_parser (2.2.1)
reline (0.3.1, default: 0.1.5)
request_store (1.5.0)
responders (3.0.1)
rest-client (2.1.0)
rexml (3.2.5, default: 3.2.3.1)
rspec (3.11.0)
rspec-core (3.11.0)
rspec-expectations (3.11.0)
rspec-mocks (3.11.0)
rspec-rails (4.1.2)
rspec-support (3.11.0)
rss (default: 0.2.8)
rubocop (1.26.0)
rubocop-ast (1.16.0)
rubocop-rails (2.13.2)
rubocop-rake (0.6.0)
rubocop-rspec (2.9.0)
ruby-progressbar (1.11.0)
ruby-vips (2.1.4)
rubygems-update (3.2.5)
samovar (2.1.4)
sassc (2.4.0)
sassc-rails (2.1.2)
sdbm (default: 1.0.0)
semantic_range (3.0.0)
shoulda-matchers (5.1.0)
simple_po_parser (1.1.5)
singleton (default: 0.1.0)
sixarm_ruby_unaccent (1.2.0)
sprockets (3.7.2)
sprockets-rails (3.4.2)
stringio (default: 0.1.0)
stripe (1.58.0)
strscan (default: 1.0.3)
table_print (1.5.7)
test-unit (3.5.3, 3.3.9)
thor (1.2.1)
tilt (2.0.10)
timecop (0.9.5)
timeout (default: 0.1.0)
timers (4.3.3)
tracer (default: 0.1.0)
traceroute (0.8.1)
turbo_test (0.1.2)
tzinfo (2.0.4)
unf (0.1.4)
unf_ext (0.0.7.7)
unicode-display_width (2.1.0)
uri (default: 0.10.0)
validate_url (1.0.13)
warden (1.2.9)
webmock (3.14.0)
webpacker (5.4.3)
webrick (default: 1.6.1)
websocket-driver (0.7.5)
websocket-extensions (0.1.5)
wisper (2.0.1)
wisper-activejob (1.0.0)
wisper-rspec (1.1.0)
xmlrpc (0.3.0)
yaml (default: 0.1.0)
zeitwerk (2.5.4)
zlib (default: 1.1.0)
```

**Comment by BenSturmfels** [comment]
> Removing `config/routes.rb` lines 292-305 appears to fix the issue, allowing the server to start up. These lines appear to be nearly identical to `gems/activestorage-6.1.5/config/routes.rb` lines 3-17 except for a minor difference in the last line.

I should mention that removing those lines causes problems when running in development with just `bin/rails server`, so it's clearly not the whole story.

**Comment by BenSturmfels** [comment]
> I should mention that removing those lines causes problems when running in development with just `bin/rails server`, so it's clearly not the whole story.

Noticed that removing these lines breaks `production` too after logging in: `ActionView::Template::Error (undefined method `rails_blob_representation_proxy_url' for #<ActionView::Base:0x0000000002d140>`

**Comment by wwahammy** [comment]
If you have a chance, add `config.active_storage.draw_routes = false` into the `config/environments/production.rb` file and see how that works.

The reason we need to repeat those lines in here is that, bizarrely, Rails ActiveStorage is totally not secured by default. `config.active_storage.draw_routes = false` in the application.rb file should prevent its use on production as well but perhaps production has a default that overrides that?

**Comment by BenSturmfels** [comment]
Thanks! I added a line like this in `config/environments/production.rb`, but still get `Invalid route name, already in use: 'rails_service_blob'  (ArgumentError)`:
```

Rails.application.configure do
  ...
  config.active_storage.draw_routes = false
end
```

**Comment by wwahammy** [comment]
I'll have to dig into this further. Unfortunately, I won't have time this week.

**Comment by wwahammy** [comment]
I have a tentative fix for this but it needs to be tested further. In config/initializers/devise.rb, add the following line:

`config.reload_routes = false`

There seems to be a weird interaction between devise and activestorage that isn't well documented. I will have to report them bug to Devise when I have the chance.

**Comment by BenSturmfels** [comment]
It's alive! Thanks so much @wwahammy. I realise this is a temporary fix, but great to be able to get past this for now.

**Comment by BenSturmfels** [comment]
(and ran `bundle install` beforehand)
