### ISSUE TITLE
[BUG] Credit card donation fails with 404 call to http://localhost:5000/cards

### ISSUE THREAD

**Issue by BenSturmfels** [houdiniproject/houdini#1067]
If I forge ahead past #1050 by temporarily hard-coding my Stripe public key directly into the template and submit the credit card form, the authorization header is all good and the POST to api.stripe.com succeeds, but I then get a 404 on `http://localhost:5000/cards` and `Uncaught TypeError: resp is undefined`. See screenshot:

![2022-03-23_17-09](https://user-images.githubusercontent.com/9541562/159635057-033f0609-fd78-483d-a82d-cd5cc07077a1.png)

Only seen when logged out at present due to another issue with `card[profile_id]` preventing me getting this far when logged in.

_Originally posted by @BenSturmfels in https://github.com/houdiniproject/houdini/issues/1050#issuecomment-1075956993_

**Comment by wwahammy** [comment]
Hey @BenSturmfels, this might be closed by #1066

**Comment by wwahammy** [comment]
So you're seeing this when logged out on the latest PR?

Have you run bin/rails assets:clobber and then bin/rails server again?

Could you send a list of the JSON calls to localhost being made in the browser? Mainly, I'd need the urls, the requests and the response.

**Comment by BenSturmfels** [comment]
@wwahammy confirming that I'm still seeing this on the `fix/donation-working` branch. Here's a HAR export of the requests from this logged-in attempt to pay by credit card. You should be able to load this into the network panel in Firefox or Chrome. I tried a few options, but couldn't find something that exported the headers/requests/responses from multiple requests.

https://owncloud.sturm.com.au/index.php/s/Q4wLgnQxWvKB6qw

**Comment by BenSturmfels** [comment]
(I did the clobber before recording the above)

**Comment by BenSturmfels** [comment]
Just a correction, I think the above 404 was due to a JavaScript donate form snippet with 127.0.0.1:5000 in (the URL that the Rails server suggests on the console) rather than localhost:5000 which seems to be hard-coded in the callback in development. So looking again, the original error on `fix/donation-working` branch was a 500 error to `/cards`:

```
method=POST path=/cards format=*/* controller=CardsController action=create status=500 error='NoMethodError: undefined method `sources' for #<Stripe::Customer:0x00000000071ad1a8>
Did you mean?  source=' duration=515.55 view=0.00 db=5.13 time=317822.18 exception=["NoMethodError", "undefined method `sources' for #<Stripe::Customer:0x00000000071ad1a8>\nDid you mean?  source="] exception_object=undefined method `sources' for #<Stripe::Customer:0x00000000071ad1a8>
Did you mean?  source=
  
NoMethodError (undefined method `sources' for #<Stripe::Customer:0x00000000071ad1a8>
Did you mean?  source=):
  
app/legacy_lib/insert_card.rb:79:in `with_stripe'
app/controllers/cards_controller.rb:12:in `create'
app/controllers/concerns/controllers/locale.rb:22:in `switch_locale'
```

After the `Stripe.api_version = '2017-06-05'` suggested in #1069, I get a 200 from `/cards` but then a 500 on the subseqent request to `/nonprofits/1/donations` with `Received unknown parameters: managed, transfer_schedule` (see below). I presume the `binding.break` is an inline debugger breakpoint and `c`'d past these. Is that right? Are you seeing the same errors on your end, or is it working for you?

```
method=POST path=/cards format=*/* controller=CardsController action=create status=200 duration=1609.22 view=2.22 db=18.11 time=318244.72 exception= exception_object=
* Locale set to 'en'
[81, 90] in ~/conservancy/houdini/app/controllers/nonprofits/donations_controller.rb
    81|       end
    82|     end
    83| 
    84|     private
    85|     def donations_params
=>  86|       binding.break
    87|       params.require(:donation).permit(:date, :amount, :recurring, :anonymous, :email, :designation, :dedication, :comment, :origin_url, :nonprofit_id, :card_id, :supporter_id, :profile_id, :campaign_id, :payment_id, :event_id, :direct_debit_detail_id, :token)
    88|     end
    89|   end
    90| end
=>#0	Nonprofits::DonationsController#donations_params at ~/conservancy/houdini/app/controllers/nonprofits/donations_controller.rb:86
  #1	Nonprofits::DonationsController#create at ~/conservancy/houdini/app/controllers/nonprofits/donations_controller.rb:21
  # and 78 frames (use `bt' command for all frames)
(rdbg) c    # continue command
[8, 17] in ~/conservancy/houdini/app/legacy_lib/insert_donation.rb
     8|   # amount, card_id, nonprofit_id, supporter_id
     9|   # designation, dedication
    10|   # recurring_donation if is recurring
    11|   def self.with_stripe(data, current_user = nil)
    12|     data = data.to_h.with_indifferent_access
=>  13|     binding.break
    14|     ParamValidation.new(data, common_param_validations
    15|                                   .merge(token: { required: true, format: UUID::Regex }))
    16| 
    17|     source_token = QuerySourceToken.get_and_increment_source_token(data[:token], current_user)
=>#0	InsertDonation.with_stripe(data={"amount"=>1000, "nonprofit_id"=>1, "sup..., current_user=nil) at ~/conservancy/houdini/app/legacy_lib/insert_donation.rb:13
  #1	Nonprofits::DonationsController#create at ~/conservancy/houdini/app/controllers/nonprofits/donations_controller.rb:21
  # and 78 frames (use `bt' command for all frames)
(rdbg) c    # continue command
  SourceToken Load (1.6ms)  SELECT "source_tokens".* FROM "source_tokens" WHERE (token = '7eac841f-7dbc-498a-85c2-01754c826507') ORDER BY "source_tokens"."token" ASC LIMIT $1  [["LIMIT", 1]]
  ↳ app/legacy_lib/query_source_token.rb:19:in `get_and_increment_source_token'
  TRANSACTION (0.4ms)  BEGIN
  ↳ app/legacy_lib/query_source_token.rb:21:in `get_and_increment_source_token'
  SourceToken Load (0.7ms)  SELECT "source_tokens".* FROM "source_tokens" WHERE "source_tokens"."token" = $1 LIMIT $2 FOR UPDATE  [["token", "7eac841f-7dbc-498a-85c2-01754c826507"], ["LIMIT", 1]]
  ↳ app/legacy_lib/query_source_token.rb:21:in `get_and_increment_source_token'
  SourceToken Update (0.9ms)  UPDATE "source_tokens" SET "total_uses" = $1, "updated_at" = $2 WHERE "source_tokens"."token" = $3  [["total_uses", 1], ["updated_at", "2022-03-28 00:52:26.784727"], ["token", "7eac841f-7dbc-498a-85c2-01754c826507"]]
  ↳ app/legacy_lib/query_source_token.rb:34:in `block in get_and_increment_source_token'
  TRANSACTION (5.9ms)  COMMIT
  ↳ app/legacy_lib/query_source_token.rb:21:in `get_and_increment_source_token'
  Card Load (0.5ms)  SELECT "cards".* FROM "cards" WHERE "cards"."id" = $1 LIMIT $2  [["id", 3], ["LIMIT", 1]]
  ↳ app/legacy_lib/insert_donation.rb:18:in `with_stripe'
  Supporter Load (0.9ms)  SELECT "supporters".* FROM "supporters" WHERE (id = 17) ORDER BY "supporters"."id" ASC LIMIT $1  [["LIMIT", 1]]
  ↳ app/legacy_lib/retrieve_active_record_items.rb:23:in `block in retrieve'
  Nonprofit Load (0.8ms)  SELECT "nonprofits".* FROM "nonprofits" WHERE (id = 1) ORDER BY "nonprofits"."id" ASC LIMIT $1  [["LIMIT", 1]]
  ↳ app/legacy_lib/retrieve_active_record_items.rb:23:in `block in retrieve'
  Nonprofit Load (0.5ms)  SELECT "nonprofits".* FROM "nonprofits" WHERE "nonprofits"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/legacy_lib/insert_donation.rb:281:in `validate_entities'
  Supporter Load (0.7ms)  SELECT "supporters".* FROM "supporters" WHERE "supporters"."id" = $1 LIMIT $2  [["id", 17], ["LIMIT", 1]]
  ↳ app/legacy_lib/insert_donation.rb:28:in `with_stripe'
   (0.5ms)  
SELECT statement, name
FROM nonprofits 
WHERE (id=1)
  ↳ app/legacy_lib/psql.rb:16:in `execute'
  CACHE Nonprofit Load (0.0ms)  SELECT "nonprofits".* FROM "nonprofits" WHERE (id = 1) ORDER BY "nonprofits"."id" ASC LIMIT $1  [["LIMIT", 1]]
  ↳ app/legacy_lib/insert_charge.rb:35:in `with_stripe'
  CACHE Supporter Load (0.0ms)  SELECT "supporters".* FROM "supporters" WHERE (id = 17) ORDER BY "supporters"."id" ASC LIMIT $1  [["LIMIT", 1]]
  ↳ app/legacy_lib/insert_charge.rb:41:in `with_stripe'
  Card Load (0.5ms)  SELECT "cards".* FROM "cards" WHERE (id = 3) ORDER BY "cards"."id" ASC LIMIT $1  [["LIMIT", 1]]
  ↳ app/legacy_lib/insert_charge.rb:47:in `with_stripe'
  CACHE Nonprofit Load (0.0ms)  SELECT "nonprofits".* FROM "nonprofits" WHERE "nonprofits"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/legacy_lib/insert_charge.rb:53:in `with_stripe'
  CACHE Supporter Load (0.0ms)  SELECT "supporters".* FROM "supporters" WHERE "supporters"."id" = $1 LIMIT $2  [["id", 17], ["LIMIT", 1]]
  ↳ app/legacy_lib/insert_charge.rb:57:in `with_stripe'
  CACHE Nonprofit Load (0.0ms)  SELECT "nonprofits".* FROM "nonprofits" WHERE "nonprofits"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/legacy_lib/stripe_account.rb:11:in `find_or_create'
method=POST path=/nonprofits/1/donations format=*/* controller=Nonprofits::DonationsController action=create status=500 error='Stripe::InvalidRequestError: Received unknown parameters: managed, transfer_schedule' duration=19592.58 view=0.00 db=15.78 time=318246.39 exception=["Stripe::InvalidRequestError", "Received unknown parameters: managed, transfer_schedule"] exception_object=(Status 400) (Request req_43VhYoIk7t2SSf) Received unknown parameters: managed, transfer_schedule
  
Stripe::InvalidRequestError (Received unknown parameters: managed, transfer_schedule):
  
app/legacy_lib/stripe_account.rb:48:in `create'
app/legacy_lib/stripe_account.rb:17:in `find_or_create'
app/legacy_lib/insert_charge.rb:69:in `with_stripe'
app/legacy_lib/insert_donation.rb:164:in `insert_charge'
app/legacy_lib/insert_donation.rb:38:in `with_stripe'
app/controllers/nonprofits/donations_controller.rb:21:in `create'
app/controllers/concerns/controllers/locale.rb:22:in `switch_locale'
```

**Comment by wwahammy** [comment]
@BenSturmfels, comment out line 69 in app/legacy_lib/insert_charge.rb I suspect that will fix it.

**Comment by wwahammy** [comment]
Also, please update to the latest on that PR, I removed the binding.break's and fixed a few other things.

**Comment by BenSturmfels** [comment]
@wwahammy awesome, with app/legacy_lib/insert_charge.rb:69 commented out I get a successful payment!

**Comment by BenSturmfels** [comment]
Now fixed on `main` following the merge of branch `wwahammy:fix/donations-working`.
