### ISSUE TITLE
[BUG] Refund fails with HTTP 500

### ISSUE THREAD

**Issue by BenSturmfels** [houdiniproject/houdini#1103]
Me again! ;) We have Houdini set up with a Stripe testing API key and I hit the "Refund" button for a payment, but it failed, showing `Error: cannot POST /nonprofits/1/charges/3/refunds (500)`.

Here's the output from the console. Appears to be an issue in `refunds_controller.rb`.
```

   (1.7ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
* Locale set to 'en'
  User Load (1.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/concerns/controllers/user/authorization.rb:71:in `administered_nonprofit'
   (1.3ms)  SELECT host_id FROM roles WHERE ("user_id" IN (1)) AND (roles.name IN ($Q$nonprofit_admin$Q$, $Q$nonprofit_associate$Q$))
  ↳ app/legacy_lib/query_roles.rb:19:in `host_ids'
  Nonprofit Load (1.1ms)  SELECT "nonprofits".* FROM "nonprofits" WHERE "nonprofits"."id" = $1 ORDER BY "nonprofits"."id" DESC LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/concerns/controllers/user/authorization.rb:73:in `administered_nonprofit'
  Nonprofit Load (0.5ms)  SELECT "nonprofits".* FROM "nonprofits" WHERE "nonprofits"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/legacy_lib/fetch_nonprofit.rb:10:in `with_params'
   (0.4ms)  SELECT host_id FROM roles WHERE ("user_id" IN (1)) AND (roles.name IN ($Q$nonprofit_admin$Q$, $Q$nonprofit_associate$Q$))
  ↳ app/legacy_lib/query_roles.rb:19:in `host_ids'
  CACHE Nonprofit Load (0.0ms)  SELECT "nonprofits".* FROM "nonprofits" WHERE "nonprofits"."id" = $1 ORDER BY "nonprofits"."id" DESC LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/concerns/controllers/user/authorization.rb:73:in `administered_nonprofit'
  CACHE Nonprofit Load (0.0ms)  SELECT "nonprofits".* FROM "nonprofits" WHERE "nonprofits"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/legacy_lib/fetch_nonprofit.rb:10:in `with_params'
   (0.8ms)  SELECT COUNT(roles) FROM roles WHERE (name IN ($Q$nonprofit_admin$Q$, $Q$nonprofit_associate$Q$)) AND ("user_id" IN (1)) AND ("host_id" IN (1))
  ↳ app/legacy_lib/query_roles.rb:11:in `user_has_role?'
method=POST path=/nonprofits/1/charges/3/refunds format=*/* controller=Nonprofits::RefundsController action=create status=500 error='ArgumentError: wrong number of arguments (given 2, expected 1)' duration=250.10 view=0.00 db=19.72 time=29792.25 exception=["ArgumentError", "wrong number of arguments (given 2, expected 1)"] exception_object=wrong number of arguments (given 2, expected 1)
  
ArgumentError (wrong number of arguments (given 2, expected 1)):
  
app/controllers/nonprofits/refunds_controller.rb:28:in `charge_params'
app/controllers/nonprofits/refunds_controller.rb:14:in `create'
app/controllers/concerns/controllers/locale.rb:22:in `switch_locale'
```

**Comment by wwahammy** [comment]
@BenSturmfels did #1107  correct this bug?

**Comment by wwahammy** [comment]
Closed by https://github.com/houdiniproject/houdini/pull/1107
