### ISSUE TITLE
[BUG] SassC::SyntaxError: Error: File to import not found or unreadable: components/event_preview_small.

### ISSUE THREAD

**Issue by BenSturmfels** [houdiniproject/houdini#1582]
When I run `bin/rake assets:precompile`, I get an error about a missing stylesheet:

`SassC::SyntaxError: Error: File to import not found or unreadable: components/event_preview_small.`

Full backtrace below. This import occurs in `app/assets/stylesheets/nonprofits/dashboard/page.css.scss`:

`@import 'components/event_preview_small';`

but no such file appears to exist in `app/assets/stylesheets/components`.  If I comment out that `@import` line, the asset compilation proceeds without errors.

* Ruby version: 2.7.8
* Node: 18.16.0 (with `NODE_OPTIONS=--openssl-legacy-provider`)

```
$ bin/rake assets:precompile
/srv/houdini/.gems/gems/net-protocol-0.2.1/lib/net/protocol.rb:68: warning: already initialized constant Net::ProtocRetryError
/usr/lib/ruby/2.7.0/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/srv/houdini/.gems/gems/net-protocol-0.2.1/lib/net/protocol.rb:214: warning: already initialized constant Net::BufferedIO::BUFSIZE
/usr/lib/ruby/2.7.0/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/srv/houdini/.gems/gems/net-protocol-0.2.1/lib/net/protocol.rb:541: warning: already initialized constant Net::NetPrivate::Socket
/usr/lib/ruby/2.7.0/net/protocol.rb:503: warning: previous definition of Socket was here
I, [2023-06-20T01:58:14.314931 #2248588]  INFO -- : Writing /srv/houdini/public/assets/widget/donate-button-157132a9ae187c137fa6dd766d1a8c60234692f796fc21cada960956fc319e2b.css
I, [2023-06-20T01:58:14.315552 #2248588]  INFO -- : Writing /srv/houdini/public/assets/widget/donate-button-157132a9ae187c137fa6dd766d1a8c60234692f796fc21cada960956fc319e2b.css.gz
I, [2023-06-20T01:58:14.323016 #2248588]  INFO -- : Writing /srv/houdini/public/assets/widget/donate-button-v2-f0018f8096f1728c594ab1eaf1862b437780db6e42fabd26421671812b33b485.css
I, [2023-06-20T01:58:14.323178 #2248588]  INFO -- : Writing /srv/houdini/public/assets/widget/donate-button-v2-f0018f8096f1728c594ab1eaf1862b437780db6e42fabd26421671812b33b485.css.gz
I, [2023-06-20T01:58:14.324695 #2248588]  INFO -- : Writing /srv/houdini/public/assets/Bitter/Bitter-Bold-e89b75b348a1ae684642650e5eaa62bf9f758e9ff9296c77808f6f59a163c8b1.woff
I, [2023-06-20T01:58:14.325913 #2248588]  INFO -- : Writing /srv/houdini/public/assets/Bitter/Bitter-Regular-b625d291f9e466b537fa56ff7e965a4aeb6eaadda1856572f999fbe93d0f33e7.woff
I, [2023-06-20T01:58:14.328039 #2248588]  INFO -- : Writing /srv/houdini/public/assets/FontAwesome/fontawesome-webfont-66db52b456efe7e29cec11fa09421d03cb09e37ed1b567307ec0444fd605ce31.woff
I, [2023-06-20T01:58:14.329137 #2248588]  INFO -- : Writing /srv/houdini/public/assets/Open_Sans/opensans-bold-webfont-85b0ba8ac2888f7d915560aaf97cf1087545240c039e7bbe7ad98aedebb4e2db.woff
I, [2023-06-20T01:58:14.330210 #2248588]  INFO -- : Writing /srv/houdini/public/assets/Open_Sans/opensans-light-webfont-be1766b58276dda7b342922f8a71939e76eb00353fb0f044b1a76694d4583dbd.woff
I, [2023-06-20T01:58:14.332130 #2248588]  INFO -- : Writing /srv/houdini/public/assets/Open_Sans/opensans-regular-webfont-704853ae58ea060d04030888f1b5fb3c8f1912e9e1eb28d047c8b69e1450953c.woff
I, [2023-06-20T01:58:14.333051 #2248588]  INFO -- : Writing /srv/houdini/public/assets/Open_Sans_Condensed/opensans-condbold-webfont-f004fe4847346504773c503e002e559b345748e874fa39f7bfcb7e5583cf78d1.woff
I, [2023-06-20T01:58:14.335527 #2248588]  INFO -- : Writing /srv/houdini/public/assets/Streamline/streamline-30px-ab2a415b1666cae49b43eedd53ae1f93cd0528b1c2ffe6548e7c49fa378f9d6e.woff
I, [2023-06-20T01:58:14.336769 #2248588]  INFO -- : Writing /srv/houdini/public/assets/favicon-566fd1fee34779f7fa232819e7a494e02d17f43eab1d671a17bbb04255bbc69f.ico
I, [2023-06-20T01:58:14.336931 #2248588]  INFO -- : Writing /srv/houdini/public/assets/favicon-566fd1fee34779f7fa232819e7a494e02d17f43eab1d671a17bbb04255bbc69f.ico.gz
I, [2023-06-20T01:58:14.337910 #2248588]  INFO -- : Writing /srv/houdini/public/assets/graphics/10x5-936673930bfca72ba8c9ec137acbe6e5cd9ce9bcc927764852e57bbd63cadf5f.jpg
I, [2023-06-20T01:58:14.338745 #2248588]  INFO -- : Writing /srv/houdini/public/assets/graphics/10x6-866a530e53770585bb5f1d48eeab5dc5191e163822c2c9853c4d6269983a152f.jpg
I, [2023-06-20T01:58:14.339610 #2248588]  INFO -- : Writing /srv/houdini/public/assets/graphics/bank-account-helper-4e8d8b611374db64c5d6f1377ba861c6a5dc57eb59ccc5da7e20e84f88c34834.png
I, [2023-06-20T01:58:14.340615 #2248588]  INFO -- : Writing /srv/houdini/public/assets/graphics/cc-security-code-988022504d4817abcc342fc87387474d7c9ef215af8cd0f3543fc2dffb83607d.png
I, [2023-06-20T01:58:14.343752 #2248588]  INFO -- : Writing /srv/houdini/public/assets/graphics/credit-card-logos-90c83dce2c8cc04ea00640b5c478ddf480e82a9de79a731229a283a8f1cffce9.png
I, [2023-06-20T01:58:14.345132 #2248588]  INFO -- : Writing /srv/houdini/public/assets/graphics/donate-elephant-78d71cbac18938e5eff6fa56b0ff1d82df330c1c0bdf6236de4fd4637a4b6a43.png
I, [2023-06-20T01:58:14.346511 #2248588]  INFO -- : Writing /srv/houdini/public/assets/graphics/half-circle-bottom-db70a25d2e240aa7f94caee5b9a43c58fd8323cb0d114bb111a12c4c1a263423.svg
I, [2023-06-20T01:58:14.346705 #2248588]  INFO -- : Writing /srv/houdini/public/assets/graphics/half-circle-bottom-db70a25d2e240aa7f94caee5b9a43c58fd8323cb0d114bb111a12c4c1a263423.svg.gz
I, [2023-06-20T01:58:14.348042 #2248588]  INFO -- : Writing /srv/houdini/public/assets/graphics/half-circle-left-ff5eb287d26dd573a3cffe40f658b08266d2e01afc3d4b456143bd47cc02974f.svg
I, [2023-06-20T01:58:14.348326 #2248588]  INFO -- : Writing /srv/houdini/public/assets/graphics/half-circle-left-ff5eb287d26dd573a3cffe40f658b08266d2e01afc3d4b456143bd47cc02974f.svg.gz
I, [2023-06-20T01:58:14.349593 #2248588]  INFO -- : Writing /srv/houdini/public/assets/graphics/half-circle-right-50ab1270eef457f4fd0526a54c25954c380d9d41f65bc13c6a66fe12291b01d9.svg
I, [2023-06-20T01:58:14.349716 #2248588]  INFO -- : Writing /srv/houdini/public/assets/graphics/half-circle-right-50ab1270eef457f4fd0526a54c25954c380d9d41f65bc13c6a66fe12291b01d9.svg.gz
I, [2023-06-20T01:58:14.350506 #2248588]  INFO -- : Writing /srv/houdini/public/assets/graphics/half-circle-top-1cb7df7e9f0b09762997678a7cebcb58c8fbea90e69bb2ac459d65545b0bb71d.svg
I, [2023-06-20T01:58:14.350642 #2248588]  INFO -- : Writing /srv/houdini/public/assets/graphics/half-circle-top-1cb7df7e9f0b09762997678a7cebcb58c8fbea90e69bb2ac459d65545b0bb71d.svg.gz
I, [2023-06-20T01:58:14.351393 #2248588]  INFO -- : Writing /srv/houdini/public/assets/graphics/icon-grip-1d1ce833384a8ec059a72c123271aa1db9e2eb4cdac857d7f9ff6c5a302e9b73.svg
I, [2023-06-20T01:58:14.351544 #2248588]  INFO -- : Writing /srv/houdini/public/assets/graphics/icon-grip-1d1ce833384a8ec059a72c123271aa1db9e2eb4cdac857d7f9ff6c5a302e9b73.svg.gz
I, [2023-06-20T01:58:14.354434 #2248588]  INFO -- : Writing /srv/houdini/public/assets/graphics/mini-amount-step-c9775ac26228fb800969303a7dd7382b8ce19a67c8347f73ef42d4441b6494b6.png
I, [2023-06-20T01:58:14.356192 #2248588]  INFO -- : Writing /srv/houdini/public/assets/graphics/one-time-c92a9b0863c19d5058280201738c1cbadef2cb750a3f701e9e5bbe445d614f36.png
I, [2023-06-20T01:58:14.357411 #2248588]  INFO -- : Writing /srv/houdini/public/assets/graphics/one-time-e4a10de96341f0fd97ba61156fa41a420e2b54f0f325be9c50a7a3cbf1ad1b32.svg
I, [2023-06-20T01:58:14.357541 #2248588]  INFO -- : Writing /srv/houdini/public/assets/graphics/one-time-e4a10de96341f0fd97ba61156fa41a420e2b54f0f325be9c50a7a3cbf1ad1b32.svg.gz
I, [2023-06-20T01:58:14.358562 #2248588]  INFO -- : Writing /srv/houdini/public/assets/graphics/recurring-3b26fb14ccccd3d162d39d10bdbf2de80df0075b1ed5766d19db88f7f801f8d6.png
I, [2023-06-20T01:58:14.359388 #2248588]  INFO -- : Writing /srv/houdini/public/assets/graphics/recurring-c6f5359c71fe54eec361606339eda4b05b95044b92e1c0c3a403dee968509e9f.svg
I, [2023-06-20T01:58:14.359531 #2248588]  INFO -- : Writing /srv/houdini/public/assets/graphics/recurring-c6f5359c71fe54eec361606339eda4b05b95044b92e1c0c3a403dee968509e9f.svg.gz
I, [2023-06-20T01:58:14.360295 #2248588]  INFO -- : Writing /srv/houdini/public/assets/graphics/white-radial-a4b8ba138a866e6a8a0feace26c2a3070a1fcabcf8f7e4506808a73f7a2697d5.png
I, [2023-06-20T01:58:14.363332 #2248588]  INFO -- : Writing /srv/houdini/public/assets/logos/houdini_project_border_64-ace92395d935f4083c3bb34f58a1cbdfc4cecd371419da1849035130c2658a47.svg
I, [2023-06-20T01:58:14.363621 #2248588]  INFO -- : Writing /srv/houdini/public/assets/logos/houdini_project_border_64-ace92395d935f4083c3bb34f58a1cbdfc4cecd371419da1849035130c2658a47.svg.gz
I, [2023-06-20T01:58:14.364708 #2248588]  INFO -- : Writing /srv/houdini/public/assets/logos/houdini_project_bug-bc16d2ce0ee9dbbfdf80c875b250cdf81d152cccd058fd0d8a4f3add77cefaca.svg
I, [2023-06-20T01:58:14.364825 #2248588]  INFO -- : Writing /srv/houdini/public/assets/logos/houdini_project_bug-bc16d2ce0ee9dbbfdf80c875b250cdf81d152cccd058fd0d8a4f3add77cefaca.svg.gz
I, [2023-06-20T01:58:14.365659 #2248588]  INFO -- : Writing /srv/houdini/public/assets/logos/houdini_project_full-a39bbd4714767be7115204c001a527a0861d7b8eca949c67d5dceca3ecb4b5fd.svg
I, [2023-06-20T01:58:14.365922 #2248588]  INFO -- : Writing /srv/houdini/public/assets/logos/houdini_project_full-a39bbd4714767be7115204c001a527a0861d7b8eca949c67d5dceca3ecb4b5fd.svg.gz
I, [2023-06-20T01:58:14.366766 #2248588]  INFO -- : Writing /srv/houdini/public/assets/logos/houdini_project_rectangle_150-4a9c7ed483cdf091a5327130dd37f3c358d9ea6c042e81e2d4a47e995b58a99a.png
I, [2023-06-20T01:58:14.367665 #2248588]  INFO -- : Writing /srv/houdini/public/assets/patterns/color-mosaic-3c804467dda77326f27a85568e5836d181a2a28ada1cf6ae101c39745a0fad5e.png
I, [2023-06-20T01:58:14.371213 #2248588]  INFO -- : Writing /srv/houdini/public/assets/screenshots/address-autocomplete-2776066f879581a32719f17026bca2bf00b6abe1e5d6c820bec5b91bb757d2a4.gif
I, [2023-06-20T01:58:14.372718 #2248588]  INFO -- : Writing /srv/houdini/public/assets/ui_components/close-f7700c8d62fa4a1939654d241a7b429195a17572a3420968b1d2bfb423b1e170.svg
I, [2023-06-20T01:58:14.372852 #2248588]  INFO -- : Writing /srv/houdini/public/assets/ui_components/close-f7700c8d62fa4a1939654d241a7b429195a17572a3420968b1d2bfb423b1e170.svg.gz
Compiling asset: campaigns/edit/page.css
I, [2023-06-20T01:58:14.380139 #2248588]  INFO -- : Writing /srv/houdini/public/assets/campaigns/edit/page-60d550ecd0b5d1221ab722fca4b5c60661c56e67f0da19cd2bf9730e91084dd1.css
I, [2023-06-20T01:58:14.380297 #2248588]  INFO -- : Writing /srv/houdini/public/assets/campaigns/edit/page-60d550ecd0b5d1221ab722fca4b5c60661c56e67f0da19cd2bf9730e91084dd1.css.gz
Compiling asset: campaigns/index/page.css
I, [2023-06-20T01:58:14.388856 #2248588]  INFO -- : Writing /srv/houdini/public/assets/campaigns/index/page-d21248f0b2724c1b7d476d0f3c020d725ad979ae3eebb8ab7525d4a0c2825513.css
I, [2023-06-20T01:58:14.389004 #2248588]  INFO -- : Writing /srv/houdini/public/assets/campaigns/index/page-d21248f0b2724c1b7d476d0f3c020d725ad979ae3eebb8ab7525d4a0c2825513.css.gz
Compiling asset: campaigns/peer_to_peer/page.css
I, [2023-06-20T01:58:14.400631 #2248588]  INFO -- : Writing /srv/houdini/public/assets/campaigns/peer_to_peer/page-b39e4a0e1b8365920e92ceb061c6045fd64d7daa2aec216b8a3aa4b5886549a1.css
I, [2023-06-20T01:58:14.400791 #2248588]  INFO -- : Writing /srv/houdini/public/assets/campaigns/peer_to_peer/page-b39e4a0e1b8365920e92ceb061c6045fd64d7daa2aec216b8a3aa4b5886549a1.css.gz
Compiling asset: campaigns/show/page.css
I, [2023-06-20T01:58:14.426929 #2248588]  INFO -- : Writing /srv/houdini/public/assets/campaigns/show/page-8b244e0e8a3c1d07dd0e8ef302bbffd5e7d099084da7cd9d9637d49719c9565b.css
I, [2023-06-20T01:58:14.427092 #2248588]  INFO -- : Writing /srv/houdini/public/assets/campaigns/show/page-8b244e0e8a3c1d07dd0e8ef302bbffd5e7d099084da7cd9d9637d49719c9565b.css.gz
Compiling asset: campaigns/supporters/index/page.css
I, [2023-06-20T01:58:14.434448 #2248588]  INFO -- : Writing /srv/houdini/public/assets/campaigns/supporters/index/page-429430d1c2b320861008d68acd4d52cfe643986bdf2fa7b9f13bc480910b66dc.css
I, [2023-06-20T01:58:14.434734 #2248588]  INFO -- : Writing /srv/houdini/public/assets/campaigns/supporters/index/page-429430d1c2b320861008d68acd4d52cfe643986bdf2fa7b9f13bc480910b66dc.css.gz
Compiling asset: common/page.css
I, [2023-06-20T01:58:14.441783 #2248588]  INFO -- : Writing /srv/houdini/public/assets/common/page-90dbd5489781c73a6b073bf01ceb4e97366d6294e28a208865a9d4fb1aa663d5.css
I, [2023-06-20T01:58:14.441931 #2248588]  INFO -- : Writing /srv/houdini/public/assets/common/page-90dbd5489781c73a6b073bf01ceb4e97366d6294e28a208865a9d4fb1aa663d5.css.gz
Compiling asset: coupons/page.css
I, [2023-06-20T01:58:14.450521 #2248588]  INFO -- : Writing /srv/houdini/public/assets/coupons/page-61e1e00d096b4fa39f3bd6fa410869bd66c19442cd3e0f974bad089f2741b694.css
I, [2023-06-20T01:58:14.450677 #2248588]  INFO -- : Writing /srv/houdini/public/assets/coupons/page-61e1e00d096b4fa39f3bd6fa410869bd66c19442cd3e0f974bad089f2741b694.css.gz
Compiling asset: events/index/page.css
I, [2023-06-20T01:58:14.459271 #2248588]  INFO -- : Writing /srv/houdini/public/assets/events/index/page-cc0243854297650c3273fd79e28076cc072a7c924033dfb3f6ca45e196be7704.css
I, [2023-06-20T01:58:14.459438 #2248588]  INFO -- : Writing /srv/houdini/public/assets/events/index/page-cc0243854297650c3273fd79e28076cc072a7c924033dfb3f6ca45e196be7704.css.gz
Compiling asset: events/show/page.css
I, [2023-06-20T01:58:14.482765 #2248588]  INFO -- : Writing /srv/houdini/public/assets/events/show/page-41b0df84c62ee245bf2df09229f709e08e4c7e4742367a3e1cbbf197d866954a.css
I, [2023-06-20T01:58:14.482933 #2248588]  INFO -- : Writing /srv/houdini/public/assets/events/show/page-41b0df84c62ee245bf2df09229f709e08e4c7e4742367a3e1cbbf197d866954a.css.gz
Compiling asset: events/stats/page.css
I, [2023-06-20T01:58:14.490047 #2248588]  INFO -- : Writing /srv/houdini/public/assets/events/stats/page-99b3f2272111499b1535977fc3a3d729da8d8f499f606a17f32a49181262d860.css
I, [2023-06-20T01:58:14.490202 #2248588]  INFO -- : Writing /srv/houdini/public/assets/events/stats/page-99b3f2272111499b1535977fc3a3d729da8d8f499f606a17f32a49181262d860.css.gz
Compiling asset: experiment/global/page.css
I, [2023-06-20T01:58:14.496014 #2248588]  INFO -- : Writing /srv/houdini/public/assets/experiment/global/page-4cbb5e4bcf1f89ddfbcad770f445a32615ef969a8feee7dc75c56506f85534c0.css
I, [2023-06-20T01:58:14.496186 #2248588]  INFO -- : Writing /srv/houdini/public/assets/experiment/global/page-4cbb5e4bcf1f89ddfbcad770f445a32615ef969a8feee7dc75c56506f85534c0.css.gz
Compiling asset: nonprofits/btn/page.css
I, [2023-06-20T01:58:14.504544 #2248588]  INFO -- : Writing /srv/houdini/public/assets/nonprofits/btn/page-5650c77caa911f5647e0950bcd5e01e5e081dbee902c324fce263b7f53b84339.css
I, [2023-06-20T01:58:14.504695 #2248588]  INFO -- : Writing /srv/houdini/public/assets/nonprofits/btn/page-5650c77caa911f5647e0950bcd5e01e5e081dbee902c324fce263b7f53b84339.css.gz
Compiling asset: nonprofits/button/page.css
I, [2023-06-20T01:58:14.518448 #2248588]  INFO -- : Writing /srv/houdini/public/assets/nonprofits/button/page-ea584e451e1abd5e72f7b4c7f7abeb312d3730c68d9f8a8174e34def5d264b9e.css
I, [2023-06-20T01:58:14.518616 #2248588]  INFO -- : Writing /srv/houdini/public/assets/nonprofits/button/page-ea584e451e1abd5e72f7b4c7f7abeb312d3730c68d9f8a8174e34def5d264b9e.css.gz
Compiling asset: nonprofits/dashboard/page.css
rake aborted!
SassC::SyntaxError: Error: File to import not found or unreadable: components/event_preview_small.
        on line 7:1 of app/assets/stylesheets/nonprofits/dashboard/page.css.scss
>> @import 'components/event_preview_small';

   ^
/srv/houdini/app/assets/stylesheets/nonprofits/dashboard/page.css.scss:7
/srv/houdini/.gems/gems/sassc-2.4.0/lib/sassc/engine.rb:50:in `render'
/srv/houdini/.gems/gems/sassc-rails-2.1.2/lib/sassc/rails/template.rb:40:in `block in call'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/utils.rb:171:in `module_include'
/srv/houdini/.gems/gems/sassc-rails-2.1.2/lib/sassc/rails/template.rb:39:in `call'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/sass_processor.rb:30:in `call'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:23:in `block in call'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/utils.rb:200:in `dfs'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:24:in `call'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:142:in `block in find'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `each'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `stat_directory'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:227:in `stat_tree'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:231:in `block in stat_tree'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `each'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `stat_directory'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:227:in `stat_tree'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:231:in `block in stat_tree'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `each'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `stat_directory'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:227:in `stat_tree'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `each'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `each'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `logical_paths'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:140:in `find'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'
/srv/houdini/.gems/gems/sprockets-rails-3.4.2/lib/sprockets/rails/task.rb:67:in `block (3 levels) in define'
/srv/houdini/.gems/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'
/srv/houdini/.gems/gems/sprockets-rails-3.4.2/lib/sprockets/rails/task.rb:66:in `block (2 levels) in define'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

**Comment by BenSturmfels** [comment]
This commit appears to be the cause:
https://github.com/houdiniproject/houdini/commit/c1660b61fe938860bad9a2e3c215ffd498ba9bb4
