### ISSUE TITLE
Event Header/Hide Header Text Bug

### ISSUE THREAD

**Issue by wendylbolm** [houdiniproject/houdini#40]
Expectations: You should always be able to modify customizations to pages that you've set. 

Reality: If you go to an Event and add a header image, you'll see an option in the event settings to hide the header text.

If you delete that image, the option to hide the header text (a checkbox) will disappear. However, if you have deigned to hide the header text, the option to show the header text will be gone, so you won't be able to add the header text back unless you upload another photo and go into the settings before you delete the photo.

**Comment by nicaloribeiro** [comment]
Hi @wendylbolm ,  @iagotheophilo  and I would like to try to resolve this issue. However, we are having some trouble getting to the bug. In our view, it is necessary to create an event to have access to customizations, but it is necessary to confirm the email in order to create an event or campaign. The problem is that we couldn't confirm the email, we didn't receive the verification email.
Is this bug still present? If so, what would be the way to try to reproduce it?
We were also looking at issue #96, but we had the same email confirmation problem.
Thank you in advance for your attention.

**Comment by marcelog5** [comment]
Hi @wendylbolm , @nicaloribeiro and I when try to create a event we are getting this error:

![Sem título](https://user-images.githubusercontent.com/48961541/134079986-7955235c-ca2b-4969-a3a5-acd60078c749.png)

and the console says:
```
app/controllers/events_controller.rb:40:in `block in create'
method=POST path=/nonprofits/2/events format=*/* controller=EventsController action=create status=500 error='SystemStackError: stack level too deep' duration=40.11 view=0.00 db=4.51 time=627.70 exception=["SystemStackError", "stack level too deep"] exception_object=stack level too deep

SystemStackError (stack level too deep):

app/controllers/application_controller.rb:59:in `render_json'
app/controllers/events_controller.rb:34:in `create'
```

this happens after filling in the fields and clicking on "Preview event"

Do you know what wee are doing wrong to get this error.

**Comment by wwahammy** [comment]
Hi there, @marcelog5, I can check into this right now!

**Comment by wwahammy** [comment]
@marcelog5 I've proposed a fix on https://github.com/houdiniproject/houdini/issues/40#issuecomment-923350246 to address this.

There is still a bug related to loading the ticket levels on the event page that I need to address.

**Comment by wwahammy** [comment]
@marcelog5 I think I've fixed loading the ticket levels. There's some quirkiness here and there but it's workable.

**Comment by wwahammy** [comment]
@marcelog5 the bug fix was merged and is in the `main` branch.

**Comment by marcelog5** [comment]
Hi @wendylbolm , when I try to update the event I'm geting this error:

![update](https://user-images.githubusercontent.com/48961541/134747321-98928f33-ea92-497a-90ab-321ad081888d.png)

He says that the End datetime cant't be blank, but the endtime is already in the field.

Do you know what I'm doing wrong.

**Comment by marcelog5** [comment]
I'm getting other error when I'm try to update a image in Header Image:

![update](https://user-images.githubusercontent.com/48961541/134747710-2f474e23-de5b-4efc-9990-40c17515669e.png)

And he stay updating forever:

![update](https://user-images.githubusercontent.com/48961541/134747797-6b9b1978-0451-49d0-83b6-21af557f3139.png)

**Comment by wwahammy** [comment]
Hey there @marcelog5, I'll try to check into what's going on today. Sorry about the issue!

**Comment by wwahammy** [comment]
Hey @marcelog5: I have an approved PR at https://github.com/houdiniproject/houdini/pull/776 which fixes this bug. It should be merged in the next few hours. Thanks for the patience and help!
