### ISSUE TITLE
[BUG] Cannot go to dashboard after creating a nonprofit. 

### ISSUE THREAD

**Issue by tony-gutierrez** [houdiniproject/houdini#557]
Get parse error when being redirected to dashboard? 

<img width="1035" alt="Screen Shot 2021-03-30 at 11 18 39 PM" src="https://user-images.githubusercontent.com/15345331/113085811-89f7fd80-91ae-11eb-8b74-d9847d38ced4.png">

**Comment by tony-gutierrez** [comment]
Looks like I can no longer run the server either:

```
=> Booting Puma
=> Rails 6.1.3.1 application starting in development 
=> Run `bin/rails server --help` for more startup options
Exiting
Traceback (most recent call last):
	59: from bin/rails:9:in `<main>'
	58: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:332:in `require'
	57: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	56: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:332:in `block in require'
	55: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	54: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	53: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	52: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	51: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	50: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/railties-6.1.3.1/lib/rails/commands.rb:18:in `<main>'
	49: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/railties-6.1.3.1/lib/rails/command.rb:50:in `invoke'
	48: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/railties-6.1.3.1/lib/rails/command/base.rb:69:in `perform'
	47: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	46: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	45: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	44: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/railties-6.1.3.1/lib/rails/commands/server/server_command.rb:135:in `perform'
	43: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/railties-6.1.3.1/lib/rails/commands/server/server_command.rb:135:in `tap'
	42: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/railties-6.1.3.1/lib/rails/commands/server/server_command.rb:144:in `block in perform'
	41: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/railties-6.1.3.1/lib/rails/commands/server/server_command.rb:37:in `start'
	40: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/railties-6.1.3.1/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
	39: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
	38: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
	37: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	36: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
	35: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
	34: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
	33: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
	32: from config.ru:5:in `block in <main>'
	31: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
	30: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:332:in `require'
	29: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:299:in `load_dependency'
	28: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:332:in `block in require'
	27: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	26: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	25: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	24: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	23: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	22: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	21: from /root/houdini/config/environment.rb:12:in `<main>'
	20: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/railties-6.1.3.1/lib/rails/application.rb:384:in `initialize!'
	19: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/railties-6.1.3.1/lib/rails/initializable.rb:60:in `run_initializers'
	18: from /usr/share/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
	17: from /usr/share/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
	16: from /usr/share/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
	15: from /usr/share/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `call'
	14: from /usr/share/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each'
	13: from /usr/share/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
	12: from /usr/share/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
	11: from /usr/share/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	10: from /usr/share/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
	 9: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/railties-6.1.3.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	 8: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/railties-6.1.3.1/lib/rails/initializable.rb:32:in `run'
	 7: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/railties-6.1.3.1/lib/rails/initializable.rb:32:in `instance_exec'
	 6: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/webpacker-5.2.1/lib/webpacker/railtie.rb:41:in `block in <class:Engine>'
	 5: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/webpacker-5.2.1/lib/webpacker.rb:35:in `bootstrap'
	 4: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/webpacker-5.2.1/lib/webpacker/commands.rb:47:in `bootstrap'
	 3: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/webpacker-5.2.1/lib/webpacker/manifest.rb:18:in `refresh'
	 2: from /root/.rvm/gems/ruby-2.7.2@fundraising/gems/webpacker-5.2.1/lib/webpacker/manifest.rb:84:in `load'
	 1: from /usr/share/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/json/common.rb:156:in `parse'
/usr/share/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/json/common.rb:156:in `parse': 783: unexpected token at '' (JSON::ParserError)
```
