### ISSUE TITLE
[BUG] Almost all sections in v2 settings page are blank. 

### ISSUE THREAD

**Issue by tony-gutierrez** [houdiniproject/houdini#559]
## Description
When going to settings on a new v2 install, the left hand menu loads, but almost all sections are blank.

## Possible Fix
I do see a 404 in console:
```
method=GET path=/nonprofits/1/users/1/email_settings format=*/* controller=EmailSettingsController action=index status=200 duration=78.21 view=0.46 db=36.03 time=42969.43 exception= exception_object=
  ↳ lib/query/query_roles.rb:11:in `user_has_role?'
   (0.6ms)  SELECT host_id FROM roles WHERE ("user_id" IN (1)) AND (roles.name IN ($Q$nonprofit_admin$Q$, $Q$nonprofit_associate$Q$))
  ↳ lib/query/query_roles.rb:19:in `host_ids'
  CACHE Nonprofit Load (0.0ms)  SELECT "nonprofits".* FROM "nonprofits" WHERE "nonprofits"."id" = $1 ORDER BY "nonprofits"."id" DESC LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/concerns/controllers/user/authorization.rb:83:in `administered_nonprofit'
  CACHE Nonprofit Load (0.0ms)  SELECT "nonprofits".* FROM "nonprofits" WHERE "nonprofits"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ lib/fetch/fetch_nonprofit.rb:10:in `with_params'
   (0.5ms)  SELECT mailchimp_token FROM nonprofit_keys WHERE ("nonprofit_id" IN (1))
  ↳ lib/query/query_nonprofit_keys.rb:12:in `get_key'
404: Nonprofit key does not exist: mailchimp_token
```

**Comment by wwahammy** [comment]
Thanks for reporting this.

This is a known bug that happened since the switch to using Webpacker.

**Comment by tony-gutierrez** [comment]
It looks like a css bug. The "display:block" of the active settings pane is not sufficient to override the 
```
.hide {
    display: none !important;
}
```
selector. 

<img width="406" alt="Screen Shot 2021-04-05 at 2 26 57 PM" src="https://user-images.githubusercontent.com/15345331/113610518-40c70400-961b-11eb-9b10-92f775ab9486.png">

**Comment by tony-gutierrez** [comment]
The panes that do work do not have the "hide" class.
