### ISSUE TITLE
[BUG] Saving any setting in v2 crashes the entire server. 

### ISSUE THREAD

**Issue by tony-gutierrez** [houdiniproject/houdini#562]
## Description
Using the chrome inspector to disable hide class, I am able to see settings panes. However making any change and trying to save crashes my server. The save is committed to the db, it seems to be something after that point. 

<img width="1378" alt="Screen Shot 2021-04-05 at 2 58 51 PM" src="https://user-images.githubusercontent.com/15345331/113613784-ad440200-961f-11eb-8fba-718e62ff763d.png">

**Comment by tony-gutierrez** [comment]
```
app/models/nonprofit.rb:177:in `as_json'
app/models/nonprofit.rb:177:in `as_json'
app/models/nonprofit.rb:177:in `as_json'
app/models/nonprofit.rb:177:in `as_json'
app/models/nonprofit.rb:177:in `as_json'
app/models/nonprofit.rb:177:in `as_json'
app/models/nonprofit.rb:177:in `as_json'
app/models/nonprofit.rb:177:in `as_json'
app/models/nonprofit.rb:177:in `as_json'
app/models/nonprofit.rb:177:in `as_json'
app/models/nonprofit.rb:177:in `as_json'
app/models/nonprofit.rb:177:in `as_json'
app/models/nonprofit.rb:177:in `as_json'
app/models/nonprofit.rb:177:in `as_json'
app/models/nonprofit.rb:177:in `as_json'
app/models/nonprofit.rb:177:in `as_json'
app/models/nonprofit.rb:177:in `as_json'
app/models/nonprofit.rb:177:in `as_json'
app/controllers/application_controller.rb:26:in `json_saved'
app/controllers/nonprofits_controller.rb:58:in `update'
```
