### ISSUE TITLE
[BUG] Nonprofit creation fails because of syntax error

### ISSUE THREAD

**Issue by clarissalimab** [houdiniproject/houdini#946]
## Description
When running `bin/rails houdini:nonprofit:create` it fails because of syntax error:

```bash
Traceback (most recent call last):
	51: from bin/rails:9:in `<main>'
	50: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	49: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	48: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
	47: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	46: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	45: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/railties-6.1.4.4/lib/rails/commands.rb:18:in `<main>'
	44: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/railties-6.1.4.4/lib/rails/command.rb:48:in `invoke'
	43: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/railties-6.1.4.4/lib/rails/command/base.rb:69:in `perform'
	42: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	41: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	40: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	39: from /home/clarissa/Programming/CommitChange/houdini/commands/rails/commands/houdini/nonprofit/create/create_command.rb:38:in `perform'
	38: from /home/clarissa/Programming/CommitChange/houdini/commands/rails/commands/houdini/nonprofit/create/create_command.rb:38:in `new'
	37: from /home/clarissa/Programming/CommitChange/houdini/lib/nonprofit_creation.rb:11:in `initialize'
	36: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:213:in `const_missing'
	35: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:558:in `load_missing_constant'
	34: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:402:in `require_or_load'
	33: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:39:in `load_interlock'
	32: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/dependencies/interlock.rb:13:in `loading'
	31: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
	30: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
	29: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:39:in `block in load_interlock'
	28: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:419:in `block in require_or_load'
	27: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:522:in `load_file'
	26: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:715:in `new_constants_in'
	25: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:523:in `block in load_file'
	24: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
	23: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
	22: from /home/clarissa/Programming/CommitChange/houdini/app/models/nonprofit.rb:5:in `<main>'
	21: from /home/clarissa/Programming/CommitChange/houdini/app/models/nonprofit.rb:240:in `<class:Nonprofit>'
	20: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/core_ext/module/concerning.rb:116:in `concerning'
	19: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/core_ext/module/concerning.rb:133:in `concern'
	18: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/core_ext/module/concerning.rb:133:in `new'
	17: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/core_ext/module/concerning.rb:133:in `initialize'
	16: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/core_ext/module/concerning.rb:135:in `block in concern'
	15: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/core_ext/module/concerning.rb:135:in `module_eval'
	14: from /home/clarissa/Programming/CommitChange/houdini/app/models/nonprofit.rb:241:in `block in <class:Nonprofit>'
	13: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:213:in `const_missing'
	12: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:558:in `load_missing_constant'
	11: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:402:in `require_or_load'
	10: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:39:in `load_interlock'
	 9: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/dependencies/interlock.rb:13:in `loading'
	 8: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
	 7: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
	 6: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:39:in `block in load_interlock'
	 5: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:419:in `block in require_or_load'
	 4: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:522:in `load_file'
	 3: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:715:in `new_constants_in'
	 2: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/activesupport-6.1.4.4/lib/active_support/dependencies.rb:523:in `block in load_file'
	 1: from /home/clarissa/.rvm/gems/ruby-2.6.4/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
/home/clarissa/.rvm/gems/ruby-2.6.4/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load': /home/clarissa/Programming/CommitChange/houdini/app/models/concerns/model/jbuilder.rb:218: syntax error, unexpected ..., expecting ')' (SyntaxError)
...	def add_builder_expansion( ... )
...	                           ^~~
/home/clarissa/Programming/CommitChange/houdini/app/models/concerns/model/jbuilder.rb:220: syntax error, unexpected ..., expecting ')'
...ions.add_builder_expansion( ... )
...                            ^~~
/home/clarissa/Programming/CommitChange/houdini/app/models/concerns/model/jbuilder.rb:230: syntax error, unexpected end, expecting end-of-input
```

## Steps to Reproduce

1. Run `bin/rails houdini:nonprofit:create`;
2. Fill in the nonprofit info. Here's how I filled mine:

```bash
What is the nonprofit's name? Dognity
What is the nonprofit's state? WI
What is the nonprofit's city? Appleton
[OPTIONAL] What is the nonprofit's public website? 
[OPTIONAL] What is the nonprofit's public e-mail? 
[OPTIONAL] What is your nonprofit's public phone number? 
What is your nonprofit's admin's name? Clarissa
What is your nonprofit's admin's email address? (It'll be used for logging in) clarissa@commitchange.com
What is the nonprofit's admin's password? 
```
3. Get the error.

**Comment by wwahammy** [comment]
Hmmm, that's a problem.

**Comment by wwahammy** [comment]
@clarissalimab the bug you're getting looks to be because you're running in Ruby 2.6. We don't support Ruby 2.6 so I'm closing.
